dist: bionic

language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

matrix:
  include:
    - elixir: 1.9
      otp_release: 22.0

env:
  - MIX_ENV=test

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile

script:
  - mix test
