version: '3.1'

services:
  db:
    image: postgres:11.5
    container_name: safira_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME:-safira_dev}
      POSTGRES_USER: ${DB_USERNAME:-safira}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_PORT: ${DB_PORT:-5432}
    ports:
      - ${DB_PORT:-5432}:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:4000
    restart: always

volumes:
  pgdata:

