app = "safira-stg"
primary_region = "mad"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "stg.seium.org"
  MIX_ENV = "stg"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
