version: '3.1'

services:
  database:
    image: postgres:11.5
    container_name: database
    env_file: .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
